### ISSUE TITLE
Your post failed to publish on Farcaster due to an error. Click 'Retry' to attempt posting again.

### ISSUE THREAD

**Issue by david30907d** [DimensionDev/firefly.mask.social#1016]
[fetch] failed to fetch: 400  https://api.neynar.com:2281/v1/submitMessage
{"errCode":"bad_request.validation_failure","presentable":false,"name":"HubError","code":3,"details":"text > 320 bytes","metadata":{"errcode":["bad_request.validation_failure"]}}
Error: [fetch] failed to fetch: 400  https://api.neynar.com:2281/v1/submitMessage
{"errCode":"bad_request.validation_failure","presentable":false,"name":"HubError","code":3,"details":"text > 320 bytes","metadata":{"errcode":["bad_request.validation_failure"]}}
    at o (https://firefly.mask.social/_next/static/chunks/1075-6ebad0cc26758c0f.js:1:8321)
    at async s (https://firefly.mask.social/_next/static/chunks/1075-6ebad0cc26758c0f.js:1:10497)
    at async I.publishPost (https://firefly.mask.social/_next/static/chunks/1075-6ebad0cc26758c0f.js:1:23497)
    at async d (https://firefly.mask.social/_next/static/chunks/app/layout-b760faa384002b0a.js:1:155783)
    at async https://firefly.mask.social/_next/static/chunks/app/layout-b760faa384002b0a.js:1:156056
    at async https://firefly.mask.social/_next/static/chunks/app/layout-b760faa384002b0a.js:1:167417
    at async Promise.allSettled (index 0)
    at async rX (https://firefly.mask.social/_next/static/chunks/app/layout-b760faa384002b0a.js:1:167255)
    at async https://firefly.mask.social/_next/static/chunks/app/layout-b760faa384002b0a.js:1:171787

**Comment by guanbinrui** [comment]
Already fixed. Post text overlength due to the length calculator returns wrong result.
