### ISSUE TITLE
Failed to mute @irfannaiffi on Farcaster

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/firefly.mask.social#1114]
## Description
[fetch] failed to fetch: 401  https://api.firefly.land/v1/user/block
{"code":401,"error":["Unauthorized"]}
Error: [fetch] failed to fetch: 401  https://api.firefly.land/v1/user/block
{"code":401,"error":["Unauthorized"]}
    at o (https://firefly-staging.mask.social/_next/static/chunks/2708-39d26da228e9953a.js:1:12843)
    at async s (https://firefly-staging.mask.social/_next/static/chunks/2708-39d26da228e9953a.js:1:15137)
    at async C.blockUser (https://firefly-staging.mask.social/_next/static/chunks/2765-7e7770da60ec78f5.js:1:60311)
    at async N.value (https://firefly-staging.mask.social/_next/static/chunks/2765-7e7770da60ec78f5.js:1:1761)
    at async https://firefly-staging.mask.social/_next/static/chunks/1720-1d90c6d94d4e42eb.js:1:58086
## Extra Information
- Version: 5.1.6
- Environment: production
- Commit Hash: 347406c
- UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
- Timestamp: 2024-05-11T10:17:10.744Z

**Comment by guanbinrui** [comment]
Fixed.
