### ISSUE TITLE
Failed to mute @553355 on Lens

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/firefly.mask.social#1137]
## Description
Cannot block someone you have already blocked: {"response":{"errors":[{"message":"Cannot block someone you have already blocked","locations":[{"line":2,"column":3}],"path":["result"],"extensions":{"code":"INTERNAL_SERVER_ERROR","stacktrace":["Error: Cannot block someone you have already blocked","    at BlockRequest.validate (/usr/src/app/packages/api-lens/lib/profile/resolvers/mutations/types/block-request.js:28:19)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async ProfileLensManagerMutationsResolver.block (/usr/src/app/packages/api-lens/lib/profile/resolvers/mutations/profile-lens-manager.js:29:9)","    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:80:24)","    at async /usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:81:26","    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:80:24)","    at async /usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:81:26","    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:80:24)"]}}],"data":null,"status":200,"headers":{}},"request":{"query":"mutation Block($request: BlockRequest!) {\n  result: block(request: $request) {\n    ... on RelaySuccess {\n      ...RelaySuccess\n    }\n    ... on LensProfileManagerRelayError {\n      ...LensProfileManagerRelayError\n    }\n  }\n}\n\nfragment RelaySuccess on RelaySuccess {\n  __typename\n  txHash\n  txId\n}\n\nfragment LensProfileManagerRelayError on LensProfileManagerRelayError {\n  __typename\n  reason\n}","variables":{"request":{"profiles":["0x015b83"]}}}}
Error: Cannot block someone you have already blocked: {"response":{"errors":[{"message":"Cannot block someone you have already blocked","locations":[{"line":2,"column":3}],"path":["result"],"extensions":{"code":"INTERNAL_SERVER_ERROR","stacktrace":["Error: Cannot block someone you have already blocked","    at BlockRequest.validate (/usr/src/app/packages/api-lens/lib/profile/resolvers/mutations/types/block-request.js:28:19)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async ProfileLensManagerMutationsResolver.block (/usr/src/app/packages/api-lens/lib/profile/resolvers/mutations/profile-lens-manager.js:29:9)","    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:80:24)","    at async /usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:81:26","    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:80:24)","    at async /usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:81:26","    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:80:24)"]}}],"data":null,"status":200,"headers":{}},"request":{"query":"mutation Block($request: BlockRequest!) {\n  result: block(request: $request) {\n    ... on RelaySuccess {\n      ...RelaySuccess\n    }\n    ... on LensProfileManagerRelayError {\n      ...LensProfileManagerRelayError\n    }\n  }\n}\n\nfragment RelaySuccess on RelaySuccess {\n  __typename\n  txHash\n  txId\n}\n\nfragment LensProfileManagerRelayError on LensProfileManagerRelayError {\n  __typename\n  reason\n}","variables":{"request":{"profiles":["0x015b83"]}}}}
    at I (https://firefly.mask.social/_next/static/chunks/7321-54cf2661185d212d.js:7:40724)
## Extra Information
- Version: 5.2.2
- Environment: production
- Commit Hash: 8788771
- UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
- Timestamp: 2024-05-12T03:51:03.634Z

**Comment by Tedko** [comment]
web上*（chrome）连续多次Mute unmute

**Comment by ChinaYangKun** [comment]
重复blocked
