### ISSUE TITLE
Your post failed to publish on Farcaster due to an error. Click 'Retry' to attempt posting again.

### ISSUE THREAD

**Issue by Shesblockchainsavvy** [DimensionDev/firefly.mask.social#1185]
## Description
private key expected 32 bytes, got 0
Error: private key expected 32 bytes, got 0
    at k (https://firefly.mask.social/_next/static/chunks/6823-47caf891d03268bc.js:1:87577)
    at O (https://firefly.mask.social/_next/static/chunks/6823-47caf891d03268bc.js:1:95034)
    at Object.sign (https://firefly.mask.social/_next/static/chunks/6823-47caf891d03268bc.js:1:95676)
    at NobleEd25519Signer.signMessageHash (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3134765)
    at e.onCreate (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3147168)
    at e.<anonymous> (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122924)
    at l (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120866)
    at Object.next (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120174)
    at https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119891
    at new Promise (<anonymous>)
    at __awaiter (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119688)
    at e._callOnCreate (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122749)
    at e.<anonymous> (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122238)
    at l (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120866)
    at Object.next (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120174)
    at https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119891
    at new Promise (<anonymous>)
    at __awaiter (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119688)
    at e.create (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122101)
    at e.<anonymous> (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3123937)
    at l (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120866)
    at Object.next (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120174)
    at https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119891
    at new Promise (<anonymous>)
    at __awaiter (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119688)
    at e.create (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3123834)
    at e.onCreate (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3148341)
    at e.<anonymous> (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122924)
    at l (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120866)
    at Object.next (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120174)
    at https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119891
    at new Promise (<anonymous>)
    at __awaiter (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119688)
    at e._callOnCreate (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122749)
    at e.<anonymous> (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122238)
    at l (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120866)
    at Object.next (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120174)
    at https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119891
    at new Promise (<anonymous>)
    at __awaiter (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119688)
    at e.create (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122101)
    at e.<anonymous> (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3123937)
    at l (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120866)
    at Object.next (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120174)
    at https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119891
    at new Promise (<anonymous>)
    at __awaiter (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119688)
    at e.create (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3123834)
    at https://firefly.mask.social/_next/static/chunks/2708-af8d7b2aa7bc1f88.js:1:28675
    at _ (https://firefly.mask.social/_next/static/chunks/2708-af8d7b2aa7bc1f88.js:1:24410)
## Extra Information
- Version: 5.2.4
- Environment: production
- Commit Hash: b604bf3
- UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
- Timestamp: 2024-05-19T08:26:04.961Z

**Comment by ChinaYangKun** [comment]
和这个一样 https://github.com/DimensionDev/firefly.mask.social/issues/1188
