### ISSUE TITLE
转帖失败。

### ISSUE THREAD

**Issue by gamez528** [DimensionDev/firefly.mask.social#1188]
## Description
private key expected 32 bytes, got 64
Error: private key expected 32 bytes, got 64
    at k (https://firefly.mask.social/_next/static/chunks/6823-47caf891d03268bc.js:1:87577)
    at O (https://firefly.mask.social/_next/static/chunks/6823-47caf891d03268bc.js:1:95034)
    at Object.sign (https://firefly.mask.social/_next/static/chunks/6823-47caf891d03268bc.js:1:95676)
    at NobleEd25519Signer.signMessageHash (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3134765)
    at e.onCreate (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3147168)
    at e.<anonymous> (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122924)
    at l (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120866)
    at Object.next (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120174)
    at https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119891
    at new Promise (<anonymous>)
    at __awaiter (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119688)
    at e._callOnCreate (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122749)
    at e.<anonymous> (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122238)
    at l (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120866)
    at Object.next (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120174)
    at https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119891
    at new Promise (<anonymous>)
    at __awaiter (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119688)
    at e.create (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122101)
    at e.<anonymous> (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3123937)
    at l (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120866)
    at Object.next (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120174)
    at https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119891
    at new Promise (<anonymous>)
    at __awaiter (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119688)
    at e.create (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3123834)
    at e.onCreate (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3150025)
    at e.<anonymous> (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122924)
    at l (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120866)
    at Object.next (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120174)
    at https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119891
    at new Promise (<anonymous>)
    at __awaiter (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119688)
    at e._callOnCreate (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122749)
    at e.<anonymous> (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122238)
    at l (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120866)
    at Object.next (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120174)
    at https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119891
    at new Promise (<anonymous>)
    at __awaiter (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119688)
    at e.create (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3122101)
    at e.<anonymous> (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3123937)
    at l (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120866)
    at Object.next (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3120174)
    at https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119891
    at new Promise (<anonymous>)
    at __awaiter (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3119688)
    at e.create (https://firefly.mask.social/_next/static/chunks/8e2471ed-2b3a2c2abcd56a6c.js:1:3123834)
    at https://firefly.mask.social/_next/static/chunks/2708-af8d7b2aa7bc1f88.js:1:30306
    at _ (https://firefly.mask.social/_next/static/chunks/2708-af8d7b2aa7bc1f88.js:1:24410)
## Extra Information
- Version: 5.2.4
- Environment: production
- Commit Hash: b604bf3
- UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
- Timestamp: 2024-05-20T01:38:42.409Z

**Comment by ChinaYangKun** [comment]
这个应该解决了

**Comment by guanbinrui** [comment]
Already fixed. This bug was caused by the length calculator returns wrong result.
