### ISSUE TITLE
Your posts failed to publish on Lens due to an error. Click 'Retry' to attempt posting again.

### ISSUE THREAD

**Issue by Jooeys** [DimensionDev/firefly.mask.social#1215]
## Description
Failed to get a token for the API key ERobe75M4z7uJFYs7GpY23ncRUJA2LLr: Too many requests: {"response":{"errors":[{"message":"Failed to get a token for the API key ERobe75M4z7uJFYs7GpY23ncRUJA2LLr: Too many requests","locations":[{"line":2,"column":3}],"path":["result"],"extensions":{"code":"INTERNAL_SERVER_ERROR","stacktrace":["Error: Failed to get a token for the API key ERobe75M4z7uJFYs7GpY23ncRUJA2LLr: Too many requests","    at Object.authenticate (/usr/src/app/node_modules/defender-base-client/lib/api/auth.js:28:15)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async Object.createAuthenticatedApi (/usr/src/app/node_modules/defender-base-client/lib/api/api.js:29:19)","    at async ApiRelayer.apiCall (/usr/src/app/node_modules/defender-base-client/lib/api/client.js:32:29)","    at async DefenderRelaySigner._signTypedData (/usr/src/app/node_modules/defender-relay-client/lib/ethers/signer.js:204:21)","    at async signPublicationTypedDataByLensManager (/usr/src/app/packages/api-lens/lib/momoka/operations/publication/sign-publication-typed-data-by-lens-manager.js:8:23)","    at async momokaPost (/usr/src/app/packages/api-lens/lib/momoka/operations/publication/post.js:198:23)","    at async MomokaLensManagerMutationsResolver.postOnMomoka (/usr/src/app/packages/api-lens/lib/momoka/resolvers/mutations/momoka-lens-manager.js:43:28)","    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:80:24)","    at async /usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:81:26","    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:80:24)","    at async /usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:81:26","    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:80:24)"]}}],"data":null,"status":200,"headers":{}},"request":{"query":"mutation CommentOnMomoka($request: MomokaCommentRequest!) {\n  result: commentOnMomoka(request: $request) {\n    ... on CreateMomokaPublicationResult {\n      ...CreateMomokaPublicationResult\n    }\n    ... on LensProfileManagerRelayError {\n      ...LensProfileManagerRelayError\n    }\n  }\n}\n\nfragment LensProfileManagerRelayError on LensProfileManagerRelayError {\n  __typename\n  reason\n}\n\nfragment CreateMomokaPublicationResult on CreateMomokaPublicationResult {\n  __typename\n  id\n  proof\n  momokaId\n}","variables":{"request":{"commentOn":"0x046486-0x02-DA-f5911146","contentURI":"ar://eJO7qwK_7lhlM414EzY2kcmJ9Cji_XByUwGpj4Jo10Y"}}}}
Error: Failed to get a token for the API key ERobe75M4z7uJFYs7GpY23ncRUJA2LLr: Too many requests: {"response":{"errors":[{"message":"Failed to get a token for the API key ERobe75M4z7uJFYs7GpY23ncRUJA2LLr: Too many requests","locations":[{"line":2,"column":3}],"path":["result"],"extensions":{"code":"INTERNAL_SERVER_ERROR","stacktrace":["Error: Failed to get a token for the API key ERobe75M4z7uJFYs7GpY23ncRUJA2LLr: Too many requests","    at Object.authenticate (/usr/src/app/node_modules/defender-base-client/lib/api/auth.js:28:15)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async Object.createAuthenticatedApi (/usr/src/app/node_modules/defender-base-client/lib/api/api.js:29:19)","    at async ApiRelayer.apiCall (/usr/src/app/node_modules/defender-base-client/lib/api/client.js:32:29)","    at async DefenderRelaySigner._signTypedData (/usr/src/app/node_modules/defender-relay-client/lib/ethers/signer.js:204:21)","    at async signPublicationTypedDataByLensManager (/usr/src/app/packages/api-lens/lib/momoka/operations/publication/sign-publication-typed-data-by-lens-manager.js:8:23)","    at async momokaPost (/usr/src/app/packages/api-lens/lib/momoka/operations/publication/post.js:198:23)","    at async MomokaLensManagerMutationsResolver.postOnMomoka (/usr/src/app/packages/api-lens/lib/momoka/resolvers/mutations/momoka-lens-manager.js:43:28)","    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:80:24)","    at async /usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:81:26","    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:80:24)","    at async /usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:81:26","    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/build/cjs/resolvers/helpers.js:80:24)"]}}],"data":null,"status":200,"headers":{}},"request":{"query":"mutation CommentOnMomoka($request: MomokaCommentRequest!) {\n  result: commentOnMomoka(request: $request) {\n    ... on CreateMomokaPublicationResult {\n      ...CreateMomokaPublicationResult\n    }\n    ... on LensProfileManagerRelayError {\n      ...LensProfileManagerRelayError\n    }\n  }\n}\n\nfragment LensProfileManagerRelayError on LensProfileManagerRelayError {\n  __typename\n  reason\n}\n\nfragment CreateMomokaPublicationResult on CreateMomokaPublicationResult {\n  __typename\n  id\n  proof\n  momokaId\n}","variables":{"request":{"commentOn":"0x046486-0x02-DA-f5911146","contentURI":"ar://eJO7qwK_7lhlM414EzY2kcmJ9Cji_XByUwGpj4Jo10Y"}}}}
    at I (https://firefly.mask.social/_next/static/chunks/7321-c14c6b024f148047.js:7:40724)
## Extra Information
- Version: 5.2.4
- Environment: production
- Commit Hash: b604bf3
- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
- Timestamp: 2024-05-21T20:59:21.557Z

**Comment by guanbinrui** [comment]
Too many requests.
