### ISSUE TITLE
Failed to like the post.

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/firefly.mask.social#1519]
## Description
[fetch] failed to fetch: 400  https://api.neynar.com:2281/v1/submitMessage
{"errCode":"bad_request.validation_failure","presentable":false,"name":"HubError","code":3,"details":"invalid signer: signer 0x16c05bf50cc065b030ea34f654293c3ba9e38c2fddf634c4827c3a8f2d49978b not found for fid 966","metadata":{"errcode":["bad_request.validation_failure"]}}
Error: [fetch] failed to fetch: 400  https://api.neynar.com:2281/v1/submitMessage
{"errCode":"bad_request.validation_failure","presentable":false,"name":"HubError","code":3,"details":"invalid signer: signer 0x16c05bf50cc065b030ea34f654293c3ba9e38c2fddf634c4827c3a8f2d49978b not found for fid 966","metadata":{"errcode":["bad_request.validation_failure"]}}
    at n (https://firefly.mask.social/_next/static/chunks/1098-0f125d7b50b85866.js:1:14603)
    at async s (https://firefly.mask.social/_next/static/chunks/1098-0f125d7b50b85866.js:1:16897)
    at async b.upvotePost (https://firefly.mask.social/_next/static/chunks/3917-c34a4b0601955cbf.js:1:44005)
    at async L.value (https://firefly.mask.social/_next/static/chunks/3917-c34a4b0601955cbf.js:1:7130)
    at async https://firefly.mask.social/_next/static/chunks/8881-5ebddaf2b39f1234.js:1:9512
## Extra Information
- Version: 5.3.3
- Environment: production
- Commit Hash: 5243c00
- UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
- Timestamp: 2024-06-19T18:21:30.228Z

**Comment by Tedko** [comment]
大概知道为啥了 某个signer被我误删了报错 没catch住
