### ISSUE TITLE
Bad Request. Please check your request.

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/firefly.mask.social#2237]
## Description
Error: [fetch] failed to fetch: 400  https://firefly.mask.social/api/frame?url=https%3A%2F%2Fmoxie-status-zl8h.vercel.app%2Fapi&action=post&post-url=https%3A%2F%2Fmoxie-status-zl8h.vercel.app%2Fapi%2Fmoxiecheck%3FinitialPath%3D%25252Fapi%26previousButtonValues%3D%252523A_Check%25252C_l
{"error":"Internal Server Error"}
    at a (https://firefly.mask.social/_next/static/chunks/7336-48dffb2d35772639.js:1:29570)
    at async s (https://firefly.mask.social/_next/static/chunks/7336-48dffb2d35772639.js:1:31904)
    at async el (https://firefly.mask.social/_next/static/chunks/3609-50a052ef5b4b1c04.js:1:43559)
    at async https://firefly.mask.social/_next/static/chunks/3609-50a052ef5b4b1c04.js:1:48070
    at async onClick (https://firefly.mask.social/_next/static/chunks/3609-50a052ef5b4b1c04.js:1:37161)
## Extra Information
- Version: 5.6.2
- Environment: production
- Commit Hash: c6ea69a
- UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
- Timestamp: 2024-08-13T03:57:02.334Z

**Comment by Tedko** [comment]
https://firefly.mask.social/post/0x363e27c51dc62b0b3353bda5584e1b50cb8be67a?source=farcaster

**Comment by guanbinrui** [comment]
Error occurs when communicate with the frame server. Try use it with the warpcast developer console.

https://warpcast.com/~/developers/frames?url=https%3A%2F%2Fmoxie-status-zl8h.vercel.app%2Fapi
