### ISSUE TITLE
Failed to send tip.

### ISSUE THREAD

**Issue by ChinaYangKun** [DimensionDev/firefly.mask.social#3232]
## Description
ConnectorChainMismatchError
    at l (https://firefly-staging.mask.social/_next/static/chunks/7627-006f9f9ff20b776b.js:11389:301574)
    at async u (https://firefly-staging.mask.social/_next/static/chunks/7627-006f9f9ff20b776b.js:11389:308796)
    at async Sa.transfer (https://firefly-staging.mask.social/_next/static/chunks/app/layout-71facbed5814a748.js:13:614576)
    at async https://firefly-staging.mask.social/_next/static/chunks/app/layout-71facbed5814a748.js:13:634395
## Extra Information
- Version: 6.4.0
- Environment: production
- Commit Hash: f3c285e
- UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
- Timestamp: 2024-11-20T04:57:53.357Z

**Comment by dudu0506** [comment]
Resolved on https://github.com/DimensionDev/firefly.mask.social/pull/3233
