### ISSUE TITLE
Failed to update profile.

### ISSUE THREAD

**Issue by ChinaYangKun** [DimensionDev/firefly.mask.social#3401]
## Description
ValidationError: fix the following issues
· "lens.attributes": Array must contain at least 1 element(s)
    at C (https://firefly-staging.mask.social/_next/static/chunks/9176-a9683a4bfca21f0d.js:5:104)
    at rv (https://firefly-staging.mask.social/_next/static/chunks/9176-a9683a4bfca21f0d.js:5:37078)
    at ts.updateProfile (https://firefly-staging.mask.social/_next/static/chunks/1567-555e610621ed8fdf.js:1:201326)
    at et (https://firefly-staging.mask.social/_next/static/chunks/373-b1cad0865f6df8c1.js:1:17780)
    at g (https://firefly-staging.mask.social/_next/static/chunks/373-b1cad0865f6df8c1.js:1:19344)
    at https://firefly-staging.mask.social/_next/static/chunks/3633-b669f80337cb22a9.js:19:57481
## Extra Information
- Version: 6.5.0
- Environment: production
- Commit Hash: 0c5caf0
- UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
- Timestamp: 2024-12-04T02:57:24.334Z

**Comment by dudu0506** [comment]
Fix on https://github.com/DimensionDev/firefly.mask.social/pull/3405
